version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=make_celery.py
      - FLASK_DEBUG=1 
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - redis
      - postgres
  celery_worker:
    build: .
    command: celery -A make_celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vincenttran
      POSTGRES_PASSWORD: associationptd
      POSTGRES_DB: celery_task